let exludedKeywordsList = [
  "2019",
  "2020",
  "accessories",
  "Airbnb",
  "akvarell",
  "alice in wonderland",
  "alienware",
  "amanda anderson",
  "amazon",
  "among us",
  "amy kamboh",
  "anime",
  "animorphia",
  "app",
  "apple",
  "apron",
  "aquarelle",
  "aquarious",
  "asus",
  "available now",
  "bag",
  "barbie",
  "basket",
  "best ",
  "binder",
  "bing",
  "blippi",
  "blue sky",
  "bluey",
  "boxclever",
  "brenda",
  "brenda nathan",
  "brite",
  "bulk",
  "bundle",
  "calendar",
  "cambrige",
  "cambridge",
  "cartoon network",
  "case",
  "catherine price",
  "celebrity",
  "cheap",
  "chronicle",
  "clapton",
  "clip folder",
  "code depesche",
  "code lock",
  "coffee",
  "coil",
  "collins",
  "combination lock",
  "copic markers",
  "courtney",
  "crayola",
  "creative haven",
  "cultivate happiness",
  "custom",
  "dairy queen",
  "daniel tiger",
  "david brainerd",
  "dell",
  "denise albright",
  "dibble pack",
  "discs",
  "disney",
  "divider",
  "dolers",
  "dollar",
  "dollars",
  "donaldson",
  "dosney",
  "dottie",
  "doug graff",
  "doug spy",
  "douglas graff",
  "draco malfoy",
  "dragonball",
  "dry erase",
  "dtudence",
  "dummies",
  "dvd",
  "eco friendly",
  "edinburgh",
  "elastic bands",
  "electronic",
  "elfe et fée",
  "elmo",
  "elsa",
  "embellishment supplies",
  "emma bridgewater",
  "emmet",
  "envelopes",
  "eono",
  "erin condren",
  "filofax",
  "firls",
  "frame",
  "franklin",
  "free",
  "funny",
  "gacha life",
  "gallon",
  "game of thrones",
  "gareth moore",
  "ghibli",
  "gift set",
  "giftset",
  "gillio",
  "girla",
  "girlss",
  "gluten free",
  "good vibes",
  "goodie bag",
  "grace valentini",
  "gruffalo",
  "hallmark",
  "handbag",
  "hanna karlzon",
  "hannah karlzon",
  "hannah lynn",
  "hard cover",
  "harley davidson",
  "harry potter",
  "hebrew",
  "hello kitty",
  "hey duggee",
  "holder",
  "holder organizer",
  "hole punch",
  "hollis",
  "i5",
  "i7",
  "icarly",
  "ideas",
  "indeme",
  "insert",
  "inserts",
  "ipad",
  "jack canfield",
  "jade summer",
  "james patterson",
  "jason momoa",
  "jd evers",
  "jess volinski",
  "jids",
  "johanna basford",
  "john smith",
  "jojo siwa",
  "jordan",
  "julia donadson",
  "julia donaldson",
  "jurassic",
  "justice league",
  "kate spade",
  "kathleen",
  "katie vernon",
  "kawaii",
  "kdp",
  "kerby rosanes",
  "keychain",
  "kikki",
  "kindle",
  "kit",
  "kit washi tape",
  "klara markova",
  "kraft",
  "kurzgesagt",
  "la times",
  "laptop",
  "larry stylinson",
  "league of legends",
  "leather",
  "lego",
  "lenovo",
  "letts",
  "lisa frank",
  "little pony",
  "locked",
  "lol",
  "lol omg",
  "looney tunes",
  "low cost",
  "magazine",
  "magic marker",
  "magic pen",
  "magnet",
  "magnetic",
  "mandalorian",
  "mario",
  "mario bros",
  "marker",
  "marvel",
  "melissa and doug",
  "melissa peck",
  "mickey mouse",
  "mike jones",
  "mincrifters",
  "minecraft",
  "minecrafters",
  "minifigure",
  "minnie mouse",
  "moleskin",
  "moleskine",
  "montessori",
  "movie",
  "mug",
  "multi",
  "multi pack",
  "multipack",
  "nannah lynn",
  "naruto",
  "natalie fox",
  "national geographic",
  "netflix",
  "new",
  "new york times",
  "ninjago",
  "nintendo",
  "nyt",
  "nytimes",
  "office depot",
  "omg",
  "on sale",
  "oprah",
  "oprah winfrey",
  "orla kiely",
  "pack",
  "paleofauna",
  "paper bag",
  "papeterie bleu",
  "parker",
  "party bags",
  "paw patrol",
  "pen",
  "pen set",
  "pencils set",
  "peppa",
  "peppa pig",
  "personalized",
  "pink slim",
  "pixar",
  "pockets",
  "pokemon",
  "poster",
  "pouch",
  "pounds",
  "princess tiana",
  "protectors",
  "protein powder",
  "puzzle pieces",
  "querkles",
  "quinn",
  "rachel cruze",
  "rachel hollis",
  "raffha",
  "raphael",
  "raya",
  "refill",
  "refillable",
  "refills",
  "rhonda",
  "ring",
  "riverdale",
  "roald dahl",
  "roblox",
  "rulia rivers",
  "rusty anderson",
  "sanrio",
  "sarah ban breathnach",
  "sdshop",
  "sdshope",
  "set",
  "set crayola",
  "shannon roberts",
  "sheffer",
  "shirt",
  "simpsons",
  "sisney",
  "slimline",
  "snacks",
  "snoopy",
  "sock",
  "sonlight",
  "spiderman",
  "Spiral",
  "stamp",
  "star wars",
  "sticker",
  "stickers",
  "storage",
  "storage bins",
  "stylist",
  "subscription",
  "sweetgirls",
  "tablets",
  "tabs",
  "tear off",
  "teen titans",
  "teresa goodridge",
  "thomas",
  "thomas kinkade",
  "tiktok",
  "todd mitchell",
  "tokidoki",
  "top",
  "tracing paper",
  "tribune",
  "tv show",
  "tv shows",
  "twin wire",
  "under",
  "usborne",
  "vampire diares",
  "vampirina",
  "van gogh",
  "video games",
  "vinyl chance",
  "wall",
  "wall clock",
  "wallet",
  "walmart",
  "watercolor",
  "watercolour paper",
  "watercolours",
  "whiteboard",
  "will shortz",
  "wimpy kid",
  "winnie the pooh",
  "wipe clean",
  "with app",
  "with case",
  "with cd",
  "with lid",
  "with lock",
  "with pens",
  "with tabs",
  "yaoi",
  "youtube",
  "zelda",
  "zipper",
  "zipper binder",
];
